---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adatechn/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp assets/index-UXj6tLRu.js $DEPLOYPATH/assets/
    - /bin/cp assets/index-hwoETQjw.css $DEPLOYPATH/assets/
