---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adatechn/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp assets/index-z59s-mW9.js $DEPLOYPATH/assets/
    - /bin/cp assets/index-xU7Tuw6t.css $DEPLOYPATH/assets/
